Eco store/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

Eco store/App_Shop/urls.py
from django.urls import path
from App_Shop import views
from django.contrib.auth import views as auth_views
app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add_product', views.add_product, name='add_product'),
    path('search', views.search, name='search'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('register_business', views.register_business, name='register_business'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('about/', views.about, name='about_page'),
    path('my_businesses/', views.my_businesses, name='my_businesses'),
    path('contact/', views.contact, name='contact_page'),
    path('business_detail/<int:pk>/', views.business_detail, name='business_detail'),
    path('delete_product/', views.delete_product, name='delete_product'),
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
]

Eco store/ecommerce_website_django/urls.py
from django.contrib import admin
from django.urls import path, include

#To show media file
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('accounts/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('about/', include('App_Shop.urls')),
    path('contact/', include('App_Shop.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eco store/App_Shop/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ('-created',)

class Business(models.Model):
    class Meta:
        verbose_name_plural='Businesses'

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,default='')
    logo = models.ImageField(upload_to='businesses/logos', default='')
    owner=models.CharField(max_length=120,default='')
    business_type = models.CharField(max_length=100,default='')
    registration_number = models.CharField(max_length=50, blank=True)
    tax_id = models.CharField(max_length=50, blank=True)
    street_address = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100, blank=True)
    #division = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    business = models.ForeignKey(Business, on_delete=models.CASCADE, default='')
    mainimage = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    brand = models.CharField(max_length=100, default="Enter the brand")
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.IntegerField()
    old_price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('-created',)

class Service(models.Model):
    business = models.ForeignKey(Business,on_delete=models.CASCADE,default='')
    name=models.CharField(max_length=120)
    image=models.ImageField(upload_to='services/images')
    description=models.TextField(default='')
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.name







class DeliveryAddress(models.Model):
   
    full_name = models.CharField( max_length=255)
    phone_number = models.CharField( max_length=20)
    company_name = models.CharField( max_length=255, blank=True)
    address_line = models.CharField( max_length=255)
    # address_line2 = models.CharField( max_length=255, blank=True)
    city = models.CharField( max_length=100)
    country = models.CharField( max_length=100)

    class Meta:
        verbose_name = ("Delivery Address")
        verbose_name_plural = ("Delivery Addresses")

    def __str__(self):
        return f"{self.full_name} - {self.address_line1}, {self.city}"
class Order(models.Model):
    name = models.CharField(max_length=20, default="")

Eco store/App_Shop/forms.py
from django import forms
from .models import Product, Category,Business,DeliveryAddress

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['business','name', 'preview_text', 'detail_text', 'category', 'price', 'old_price', 'mainimage']
    name=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter name of product',
        'class':'box'
    }))
    preview_text=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Preview text',
        'class':'box'
    }))
    detail_text=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Product Description',
        'class':'box'
    }))
   
    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        # Restrict category choices if needed (optional)
        self.fields['category'].queryset = Category.objects.all()  # Get all categories

class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = ['name','owner', 'business_type', 'registration_number', 'tax_id', 'city', 'country','logo']
    name=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter Business name',
        'class':'box'
    }))
    owner=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your name',
        'class':'box'
    }))
    business_type=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter type of business',
        'class':'box'
    }))
    registration_number=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter Reg Number',
        'class':'box'
    }))
    tax_id=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter Tax ID',
        'class':'box'
    }))
    city=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter current city',
        'class':'box'
    }))
    country=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter country',
        'class':'box'
    }))
    
    


class DeliveryAddressForm(forms.ModelForm):
    class Meta:
        model=DeliveryAddress
        fields=['full_name','phone_number','company_name','address_line','city','country']
    full_name=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your names',
        'class':'box'
    }))
    phone_number=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your tel number',
        'class':'box'
    }))
    company_name=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter company name',
        'class':'box'
    }))
    address_line=forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Enter your address line',
        'class':'box'
    }))
    # address_line2=forms.CharField(widget=forms.EmailInput(attrs={
    #     'placeholder':'Enter address line 2',
    #     'class':'box'
    # }))
    city=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your current city',
        'class':'box'
    }))
    country=forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Enter your country',
        'class':'box'
    }))
    

Eco store/App_Shop/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib import auth
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User
from django.contrib import messages
from .forms import ProductForm,BusinessForm,DeliveryAddressForm
from django.contrib.auth.models import User
# Import Views
from django.views.generic import ListView, DetailView

# Import Models
from App_Shop.models import *

# Mixins
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class Home(ListView):
    model = Product
    template_name = 'App_Shop/home.html'

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'App_Shop/product_detail.html'


def add_product(request):
   
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)  # Include uploaded files
        if form.is_valid():
            new_product = form.save()  # Use form.save() for validated data
            messages.success(request, 'Product was added succesfully ')

            # Success message or redirect to product detail page
            return redirect('/') # Redirect with ID

        else:
            # Handle form errors (optional: display in the template)
            return render(request, 'App_Shop/add_product.html', {'form': form, 'categories': Category.objects.all()})
    else:
        form = ProductForm()  # Create an empty form for initial display
    return render(request, 'App_Shop/add_product.html', {'form': form, 'categories': Category.objects.all()})

def register_business(request):
    if request.method=='POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            new_business=form.save()
            messages.success(request, 'Business was registered succesfully ')
            return redirect('/')
        
        
    else:    
        form = BusinessForm()
        return render(request,'App_Shop/register_business.html',{'form':form})
    

def search(request):
    if request.method=='POST':
        searched=request.POST['search']
        searched=Product.objects.filter(name__icontains=searched)
        if not searched:
            messages.success(request,'That product does not exist, please try again')
            return render(request,'App_Shop/search.html',{})
        else:
            return render(request,'App_Shop/search.html',{'searched':searched})
    else:    
        return render(request,'App_Shop/search.html')
    

def checkout(request):
    
    form = DeliveryAddressForm()
    if request.method=='POST':
        form=DeliveryAddressForm(request.POST)
        if form.is_valid():
            form.save()

    else:
        form=DeliveryAddressForm()

    return render(request,'App_Shop/checkout.html',{'form':form})


def orders(request):
    return render(request,'App_Shop/order.html')


def about(request):
    return render(request,'App_Shop/about.html')

def contact(request):
    return render(request,'App_Shop/contact.html')

def my_businesses(request):
    businesses=Business.objects.all()
    return render(request, 'App_Shop/my_businesses.html',{'businesses':businesses})


def business_detail(request, pk):
    business = Business.objects.get(id=pk)
    return render(request,'App_Shop/business_detail.html', {'business':business})

def delete_product(request):
    return render(request,'App_Shop/delete_product.html')

def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    return redirect(('/'))

Eco store/templates/App_Shop/about.html
{% extends 'base.html' %}

{% block title_block %}About Us{% endblock %}
{% block body_block %}

<style>
  body {
    font-family: sans-serif;
    margin: 0;
    padding: 0;
    background-color:wheat;
    
  }
  main {
    margin: auto;
    height: auto;
    padding: 50px 0;
  }
  
  section {
    display: flex;
    position: relative; 
  }
  
  .about-content {
    flex: 2;
    padding: 20px;
    background-color: rgba(156, 123, 123, 0.8);
    border-radius: 4px;
    background: transparent;
  }
  
  .team-photo-container {
    flex: 1;
    padding-top: 80px;
    position: relative; 
    
  }
  
  .team-photo-container img{  
   height: 400px;
   width: 300px;
  }
  h2{
    color: gray;
    text-transform: uppercase;
    font-weight: 600;
  }
 
</style>

  <main>
    <section class="about-us">
      
      <div class="about-content">


        <div class="we">
          <h2><i class="ri-task-line"></i>Our Mission</h2>
          <p>Our mission is to provide quality online business services to our clients or customers</p>
          <h2>Our Team<i class="ri-team-line"></i></h2>
          <p>We are a great team that work together and headed by our Leader Kamuli Bob</p>
        </div>
        <div class="reachus">
          <h2></i><i class="ri-contacts-book-2-line"></i>Contact Us<i class="ri-contacts-line"></i></h2>
          <p>Contact phone: 0742098888</p>
          <p>Email Address: eco@gmail.com</p>
          <h2>Eco-Store Info<i class="ri-information-fill"></i></h2>
          <p>Eco- Store is an online website that enables businessmen to manage their businesses online</p>
          <p>It helps our customers to conduct online businesses</p>
        </div>
      </div>
      <div class="team-photo-container">
        <img src="../static/css/group.jpeg" alt="Team Photo">
      </div>
    </section>
  </main>

{% endblock %}

Eco store/templates/App_Shop/add_product.html
{% extends "base.html" %} {% block body_block %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Add Product</title>
    <style>
      body{
        font-family: sans-serif;
        font-size: 18px;
        text-align: center;
        background-color: whitesmoke;
      }
      .box{
        background: none;
        display: flex;
        width: 500px;
        display: block;
        padding: 10px;
        border-left: none;
        border-top: none;
        border-right: none;
        border-bottom: 1px solid blue;
        transition: 1s ease;
        

      }
      .form{
        text-align: justify;
        background: hsl(209, 34%, 87%);
        width: 600px;
        height: 750px;
        margin:  auto;
        /* padding:12px 20px; */
        border-radius: 20px;
        border: 1px solid white;
        align-items: center;
        padding: 50px;
        box-shadow: 15px 20px 20px rgb(139, 137, 137); 
      }
      .btn{
        font-size: 20px;
        font-family: sans-serif;
        height: 50px;
        width: 300px;
        padding: 10px 20px;
        display: block;
        border: 0;
        outline: none;
        margin: auto;
        color: whitesmoke;
        background: #0400ff;
        margin-top: 10px;
        border-radius: 15px;
        transition: 0.3s ease;
      }
      h1{
        font-size: 40px;
        font-family: sans-serif;
        font-style: oblique;
        color: black;
      }
      .btn:hover{
        opacity: 0.8;
      }
    </style>
  </head>
  <body>
    <h1>Add Product</h1>
   
    <br><br>
    <form action="" method="POST" enctype="multipart/form-data" class="form">

      {% csrf_token %} {{ form.as_p }}
      <button class="btn" type="submit">Add Product</button>
    </form>
  </body>
</html>
<br /><br /><br /><br /><br /><br /><br />

{% endblock %}

Eco store/templates/App_Shop/business_detail.html
{% extends 'base.html' %}


{% block body_block %}
<style>
    form{
        background-color: aliceblue;
        border: 1px solid rgb(173, 163, 163);
        border-radius: 5px;
        width: 500px;
        margin: 80px 350px;
        padding: 10px;
        box-shadow: 15px 20px 20px #504e4eee;
        /* padding-top: 50px; */
    }
</style>

<form action="">
    <h1 style="text-transform: uppercase; text-align: center;">{{business.name}}</h1>
    <p>owned by {{business.owner}}</p>
    <p>it is a {{business.business_type}} business</p>
    <p>Located in {{business.city}} city</p>
    
</form>

{% endblock %}

Eco store/templates/App_Shop/complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="5; url={% url 'App_Shop:home' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Payment Status</title>
</head>
<body>
    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    
</body>
</html>

Eco store/templates/App_Shop/delete_product.html
{% extends 'base.html' %}

{% block body_block %}
  <h1>Delete Product</h1>
  <form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this product?</p>
    <button type="submit" class="btn btn-danger">Delete</button>
    <a href="{% url 'App_Shop/product_detail' product.pk %}" class="btn btn-secondary">Cancel</a>
  </form>
{% endblock %}

Eco store/templates/App_Shop/home.html
{% extends "base.html" %}
{% load static %}
{% block body_block %}

<style>
    * {
        box-sizing: border-box;
    }

    .container {
        width: 200%;
        /* margin: 0; */
        padding: 0;

    }

    body {
        width: 100%;
        height: 100%;
        /* margin: 0; */
        padding: 0;
        font-family: Arial, Helvetica, sans-serif;
        font-style: normal;
        background-color: white;

    }

    h2 {
        text-align: center;
        color: black;
        font-size: 60px;
        font-style: oblique;

    }

    .action-wrap {
        background-color: wheat;
        border: 2px solid whitesmoke;
        border-radius: 5px;
    }

    .info-wrap {

        background-color: whitesmoke;
        border: 1px solid whitesmoke;
        border-radius: 5px;
    }

    .card {
        border-radius: 5px;
        box-shadow: 20px 15px 20px rgb(223, 236, 243);

    }

    .col-md-6 {
        transition: 0.3s;
    }

    .col-md-6:hover {
        transform: translateY(-5px);
    }

    .welcome {
        display: block;
        font-family: sans-serif;
        font-size: 20px;
        color: rgb(240, 10, 10);

    }

    img {
        height: 350px;
        width: 600px;
    }


    .box {
        display: none;
        margin: 0 auto;
        /* center the image containers */
        width: 100%;
        /* box-shadow: 0 15px 30px rgba(0, 0, 0, 0.30), 0 11px 8px rgba(0, 0, 0, 0.22); */
        /* material box shadow */
        margin-bottom: 20px;
        transition-duration: 1s;
        cursor: pointer;
        height: auto;

    }

    .box:hover {
        width: 90%;
        box-shadow: 0 18px 36px rgba(0, 0, 0, 0.30), 0 14px 11px rgba(0, 0, 0, 0.22);
    }

    .container-slide .box img {
        vertical-align: middle;
        width: 100%;
        height: 400px;
    }


    .container-slide {
        position: relative;
        max-width: 1000px;
        margin: auto;
    }


    .row {
        padding: 0;
    }
</style>
<div class="container my-5">
    <div class="welcome">
        <h1 style="color: orangered; font-style: italic;"><strong>Welcome to Eco store</strong></h1>

    </div>
    <section id="hero">

        <div class="container-slide">
            <div class="box w3-animate-right">
                <img src="../static/css/PIC1.svg" alt="">
            </div>
            <div class="box w3-animate-left">
                <img src="../static/css/pic2.svg" alt="">
            </div>
            <div class="box w3-animate-top">
                <img src="../static/css/PIC3.svg" alt="">
            </div>
            <script>
                let slideindex = 1
                showslides();
                function showslides() {
                    let i;
                    let slides = document.getElementsByClassName('box');
                    for (i = 0; i < slides.length; i++) {
                        slides[i].style.display = "none";
                    }
                    slideindex++;
                    if (slideindex > slides.length) {
                        slideindex = 1;
                    }
                    slides[slideindex - 1].style.display = "block";
                    setTimeout(showslides, 2000);
                }
            </script>
    </section>
    <h2><strong>Featured Products</strong></h2>
    <div class="row">
        {% for product in object_list %}
        <a href="{% url 'App_Shop:product_detail' pk=product.pk %}">
            <div class="col-md-6 col-sm-12 col-lg-3">
                <figure class="card card-product">
                    <div class="img-wrap">
                        <img src="/media/{{product.mainimage}}" style="width: 100%; height:300px;">
                    </div>
                    <figcaption class="info-wrap">
                        <h6 class="title"><a href="" style="color:black">{{product.name}}</a></h6>
                        <div class="action-wrap">
                            <div class="price-wrap h5">
                                <span class="price-new" style="color: black; font-size: 23px;">Ugx.
                                    {{product.price}}</span>
                                <span class="price-old" style="color: red; font-size: 20px;">Ugx.
                                    {{product.old_price}}</span>
                            </div>
                        </div>
                    </figcaption>

                </figure>
            </div>
        </a>

        {% endfor %}
    </div>
    <h2><strong>Most trending Products</strong></h2>
    <div class="row">
        {% for product in object_list %}
        <a href="{% url 'App_Shop:product_detail' pk=product.pk %}">
            <div class="col-md-6 col-sm-12 col-lg-3">
                <figure class="card card-product">
                    <div class="img-wrap">
                        <img src="/media/{{product.mainimage}}" style="width: 100%; height:300px;">
                    </div>
                    <figcaption class="info-wrap">
                        <h6 class="title"><a href="" style="color:black">{{product.name}}</a></h6>
                        <div class="action-wrap">
                            <div class="price-wrap h5">
                                <span class="price-new" style="color: black; font-size: 23px;">Ugx.
                                    {{product.price}}</span>
                                <span class="price-old" style="color: red; font-size: 20px;">Ugx.
                                    {{product.old_price}}</span>
                            </div>
                        </div>
                    </figcaption>

                </figure>
            </div>
        </a>

        {% endfor %}
    </div>
</div>

{% endblock %}

Eco store/templates/App_Shop/my_businesses.html
{% extends 'base.html' %}

{% block body_block %}
<style>
    form{
        background-color: whitesmoke;
        text-transform: uppercase;
        border: 1px solid whitesmoke;
        border-radius: 8px;
        width: 400px;
        height: auto;
        margin: 100px 350px;
        padding: 5px;
        font-weight: 500;
        font-size: 20px;
        box-shadow: 10px 10px rgb(192, 189, 189);
    }
</style>

<form action="">
    <h3 style="text-align: center;">LIST OF BUSINESSES</h3>
        {% for business in businesses %}
    <li>
        <a href="{% url 'App_Shop:business_detail' business.pk %}">{{business.name}}</a>
        {% endfor %}
    </li>

</form>
{% endblock %}

Eco store/templates/App_Shop/order.html
{% extends 'base.html' %}
{% block body_block %}
<style>
  h2{
    font-size: 40px;
    font-style: oblique;
    color: black;
    text-align: justify;
  }
  .card{
    border-radius: 20px;
  }
  .table{
    border-radius: 20px;
  }
  .badge{
    font-size: 20px;
  }
  .table td, .table th {
    padding: .75rem;
    vertical-align: top;
    border-top: 1px solid #d3d9df;
  }
</style>
<div class="container mt-5">
  <h2 class="text-center"><strong>Your Orders</strong></h2>
  <div class="row">
    <div class="col-md-12">
      <div class="card mt-5" style="height:auto">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Order Id</th>
                <th scope="col">Products</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {% for order in orders %}
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="#">{{ order.orderId }}</a></td>
                <td>
                  {% for item in order.orderitems.all %} {{item}} <br> {% endfor %}
                </td>
                <td><span class="badge badge-primary">Processing Your Order</span></td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-12 my-5 text-center">
      <a href="{% url 'App_Shop:home' %}" style="text-decoration: none; color: green; font-size: 40px; background-color: whitesmoke;">Bact to Home</a>
    </div>
  </div>
</div>
{% endblock %}

Eco store/templates/App_Shop/payment.html
{% extends 'base.html'%}
{% block body_block %}
Payment
</div><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

Eco store/templates/App_Shop/product_detail.html
{% extends 'base.html'%}
{% block body_block %}
<style>

</style>
<div class="container my-5">
    <div class="card">
        <div class="row">
            <aside class="col-sm-5 border-right">
                <article class="gallery-wrap">
                    <div class="img-big-wrap">
                        <div>
                            <a href="#"><img src="/media/{{object.mainimage}}" style="width:450px"></a>
                        </div>        
                    </div>
                </article>
            </aside>
            <aside class="col-sm-7">
                <article class="card-body p-5">
                    <h3 class="title mp-3">{{object.name}}</h3>
                    <p class="price-detail-wrap">
                        <span class="price h3 text-warning">
                            <span class="currency">Ugx. </span><span class:"num">{{object.price}}</span>
                        </span>
                    </p>
                    <dl class="item-property">
                        <dt style="font-size: 40px; color: black;">Description</dt>
                        <dd>
                            <p>{{object.detail_text|linebreaks}}</p>
                        </dd>
                    </dl>
                    <a href="{% url 'App_Order:add' pk=object.pk %}" class="btn btn-lg btn-outline-primary text-uppercase"><i class="fas fa-shopping-cart"></i>Add to Cart</a>
                    <a href="{% url 'App_Shop:delete_product' object.pk %}" class="btn btn-danger">Delete</a>
                </article>
            </aside>
        </div>
    </div>
</div><br><br><br><br><br><br><br><br><br><br><br><br><br></div><br><br><br><br><br><br><br><br><br><br><br><br><br></div><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock %}

Eco store/templates/App_Shop/search.html
{% extends "base.html" %} {% block body_block %}
<style>
    body{
        font-family: sans-serif;
        text-align: center;
        /* background-image: url('../static/css/search.jpeg'); */
    }
    form{
        width: 750px;
        height: 300px;
        margin: auto;
        font-weight: 800;
        font-size: 40px;
        background: silver;
        border-radius: 20px;
        margin-top: 30px;
        
    }
    .btn{
        width: 150px;

        background-color: blue;
        font-weight: 600;
        color: white;
        padding-bottom: 10px;
        font-size: 18px;
        border-radius: 15px;
        transition: 0.3s ease;
    }
    .btn:hover{
        background-color: rgb(61, 233, 26);
    }
    .see{
        border: 2px solid black;
        border-radius: 10px;
        width: 400px;
        padding: 10px 5px;
        font-size: 18px;
        height: 35px;
        padding-bottom: 8px;
    }
    .text{
        margin-left: 5px;
    }
    .action-wrap{
        background-color: wheat;
        border: 2px solid whitesmoke;
        border-radius: 5px;
    }
    .info-wrap{
        
        background-color: whitesmoke;
        border: 1px solid whitesmoke;
        border-radius: 5px;
    }
    .col-md-6{
        transition: 0.4s;
    }
    .col-md-6:hover{
        transform: translateY(-5px);
    }
</style>

<h1 style="color: black; font-size: 30px; font-style: oblique;"><strong>Search Products</strong></h1>
<form action="" method="POST">
  {%csrf_token%}
  <p><span>Find Anything in <span style="color:red; width:50px;">ec</span><span style="color:green;">oS</span><span
    style="color:blue;">TO</span><span style="color:gold;">RE</span></span></p>
  <input type="text" class="see" placeholder="Search here..." name="search" />
  <button type="submit" class="btn">GO</button>
</form>

{%if searched%} 

{%for product in searched%} 
<a href="{% url 'App_Shop:product_detail' pk=product.pk %}" style="color:black">
<div class="container my-5">
    
    <div class="row">
        
        <div class="col-md-6 col-sm-12 col-lg-3">
           
                <figure class="card card-product">
                    <div class="img-wrap">
                        <img src="/media/{{product.mainimage}}" style="width: 100%; height:300px;">
                    </div>
                    
                        <figcaption class="info-wrap">
                            <h6 class="title">{{product.name}}</h6>
                            <div class="action-wrap">
                                <div class="price-wrap h5">
                                    <span class="price-new">Ugx. {{product.price}}</span>
                                    <span class="price-old">Ugx. {{product.old_price}}</span>
                                </div>
                            </div>
                        </figcaption>
                    

                </figure>
            
        </div>     
        
    </div>
</div></a>
{%endfor%}

 {%endif%}
<br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
{% endblock %}