Eco store/App_Login/urls.py
from django.urls import path
from App_Login import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

Eco store/App_Order/urls.py
from django.urls import path
from App_Order import views

app_name = 'App_Order'

urlpatterns = [
    path('add/<pk>', views.add_to_cart, name='add'),
    path('cart/', views.cart_view, name='cart'),
    path('remove/<pk>', views.remove_from_cart, name='remove'),
    path('increase/<pk>/', views.increase_cart, name='increase'),
    path('decrease/<pk>/', views.decrease_cart, name='decrease'),
]

Eco store/App_Shop/urls.py
from django.urls import path
from App_Shop import views
from django.contrib.auth import views as auth_views
app_name = 'App_Shop'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('add_product', views.add_product, name='add_product'),
    path('search', views.search, name='search'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders, name='orders'),
    path('register_business', views.register_business, name='register_business'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('about/', views.about, name='about_page'),
    path('my_businesses/', views.my_businesses, name='my_businesses'),
    path('contact/', views.contact, name='contact_page'),
    path('business_detail/<int:pk>/', views.business_detail, name='business_detail'),
    path('delete_product/', views.delete_product, name='delete_product'),
    path('product/<int:pk>/delete/', views.delete_product, name='delete_product'),
]

Eco store/ecommerce_website_django/urls.py
from django.contrib import admin
from django.urls import path, include

#To show media file
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('App_Shop.urls')),
    path('accounts/', include('App_Login.urls')),
    path('shop/', include('App_Order.urls')),
    path('about/', include('App_Shop.urls')),
    path('contact/', include('App_Shop.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eco store/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">  
    <title>{% block title_block %} Eco store {% endblock %}</title>
    <style>
        .card{
            height: 350px;
        }
        .card-product:after{
            content: "";
            display: table;
            clear: both;
            visibility: hidden;
        }
        .card-product .price-new, .card-product .price{
            margin-right: 5px;
        }
        .card-product .price-old{
            color: #999;
            text-decoration: line-through;
        }
        .card-product .img-wrap{
            border-radius: 3px 3px 0 0;
            overflow: hidden;
            position: relative;
            height: 220px;
            text-align: center;
        }
        .card-product .img-wrap img{
            max-height: 100%;
            max-width: 100%;
            object-fit: cover;
        }
        .card-product .info-wrap{
            overflow: hidden;
            padding: 16px;
            border-top: 1px solid #eee;
        }
        .card-product .action-wrap{
            padding-top: 4px;
            margin-top: 4px;
        }
        .card-product .bottom-wrap{
            padding: 15px;
            border-top: 1px solid #eee;
        }
        .card-product .title{
            margin-top: 0px;
        }

 
        .last{
            text-align: center;
            font-family: sans-serif;
            font-size: 18px;
            color: #000;
        }
        .last a{
            text-decoration: none;
            color: #000;
        }
        .last a:hover{
            color: #000;
        }
        .container{
            margin-top: 100px;
        }
        .messages{
            margin-top: 100px;
        }
        .messages .alert{
            margin-bottom: 10px;
        }
        .messages .alert button{
            float: right;
        }
        .nav ul{
            list-style-type:none;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="container">
        <div class="messages container mt-2">
            {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }}{% endif %}" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">X</span>
                        </button>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        {% block body_block %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <footer style="background:silver; height:auto; padding:15px;">
        <div class="nav">
           <ul>
              <li><a class="active" href="{%url 'App_Shop:home'%}"><span>Home<i class="ri-home-4-line"></i></span></a></li><br>
              <li><a href="#"><span>Sign in/Register</span></a></li><br>
              <li><a href="/about"><span>About Us<i class="ri-team-line"></i></span></a></li><br>
              <li><a href="/contact"><span>Contact Us<i class="ri-team-line"></i></span></a></li><br>
              <!-- <li><a href="/contact"><span>Help and Contact<i class="ri-contacts-book-3-fill"></i></span></a></li><br> -->
           </ul>
        </div>
        <hr><br>
        <div class="last">
            <p style="font-size: 20px; color: red;">find us on</p>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <a href="#" class="fa fa-facebook"></a>
            <a href="#" class="fa fa-twitter"></a>
            <a href="#" class="fa fa-instagram"></a>
            <a href="#" class="fa fa-whatsapp"></a>
        </div>
        <div style="text-align:center;">
           <a href="#">Privacy</a>,<a href="#">User Agreement</a>,<a href="#">Cookies&Adchoice</a><br>
           <p>&copy 2024 EcoStore<i class="ri-store-line"></i></p><br>
        </div><br>
     </footer>
</body>
</html>

Eco store/templates/navbar.html
{% load cart_tag %}
<link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
<style>
    .nav-link{
        border-radius: 10px;
    }
   
    .nav-link:hover{
        background-color: greenyellow;
        text-decoration: none;
    }
    .search{
        margin: auto;
        color: black;
        border-radius: 10px;
        border: 1px solid whitesmoke;
        width: 200px;
        text-align: center;
        margin-left: 110px;
        height: 45px;
        font-size: 30px;
        transition: 0.4s ease;
    }
    .search:hover{
        background-color: grey; 
    }
    .nav-item{
        margin-right: auto;
    }
    .dropdown-item{
        color: blue;
        padding: 5px;
        font-weight: 300;
        transition: 0.3s ease;
    }
    .dropdown-item:hover{
        background-color: rgb(219, 146, 146);
        
    }

</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'App_Shop:home'%}"><h2><span style="color:red; width:50px;">ec</span><span style="color:green;">oS</span><span
            style="color:blue;">TO</span><span style="color:gold;">RE<i class="ri-store-line"></i></span></h2></a>
            <a class="search" href="{% url 'App_Shop:search'%}">Search</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span
                class="navbar-toggler-icon"></span> </button> 
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Order:cart' %}"><i class="fa fa-shopping-cart" aria-hidden="true"></i><span class="badge badge-light">{{request.user | cart_total}}</span>
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'App_Login:profile'%}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{%url 'App_Shop:orders'%}">Orders</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Shop:add_product'%}">Add Product</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Shop:register_business'%}">Register a Business</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Shop:my_businesses' %}">Your Businesses</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'App_Login:logout'%}">Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:signup' %}">Signup</a>
                    <a class="nav-link" href="{% url 'App_Login:login'%}">Login</a>
                </li>
                {% endif %}
            </ul>
    </div>
</nav>